# Generated by Django 3.2.6 on 2022-12-16 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('folio', models.TextField()),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_estado_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_fase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('url', models.TextField()),
                ('icono', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('ind_url', models.BooleanField(default=True)),
                ('modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacion_modulo_padre', to='proyecto.modulo')),
            ],
            options={
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
                ('metadatos', models.JSONField()),
            ],
            options={
                'db_table': 'parametro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
                ('ind_asignable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('metadatos', models.JSONField()),
                ('ruta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.documento')),
                ('estado_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadodocumento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_version_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'version_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSalidaReporte',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_tipo_salida_reporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tipo_salida_reporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('ind_archivo', models.BooleanField(default=True)),
                ('formato', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_tipo_entrada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tipo_entrada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('mnemonico', models.CharField(max_length=10)),
                ('folio_correlativo', models.IntegerField()),
                ('ruta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_tipo_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_seccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReporteConfigurable',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('codigo_fuente', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_reporte_configurable', to=settings.AUTH_USER_MODEL)),
                ('tipo_salida_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tiposalidareporte')),
            ],
            options={
                'db_table': 'reporte_configurable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('accion', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metadatos', models.JSONField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaseActividadTipoEntrada',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.actividad')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.fase')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_face_actividad_tipo_entrada', to=settings.AUTH_USER_MODEL)),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoentrada')),
            ],
            options={
                'db_table': 'fase_actividad_tipo_entrada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaseActividadRespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('ind_publicada', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fase_actividad_tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.faseactividadtipoentrada')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_face_actividad_respuesta_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fase_actividad_respuesta_persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaseActividadRespuestaEntrada',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('orden', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fase_actividad_tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.faseactividadtipoentrada')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_face_actividad_respuesta_entrada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fase_actividad_respuesta_entrada',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.seccion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipodocumento'),
        ),
        migrations.CreateModel(
            name='ConfiguracionBase',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('metadatos', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_configuracionbase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_base',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BitacoraFaseActividadRespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bitacora_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.bitacorafaseactividadrespuestausuario')),
                ('fase_actividad_respuesta_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.faseactividadrespuestausuario')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_bitacora_face_actividad_respuesta_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_fase_actividad_respuesta_persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuarioActivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfil_activo_perfil', to='proyecto.perfil')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_usuario_perfil_actibo', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_perfil_activo',
                'managed': True,
                'unique_together': {('perfil_id', 'usuario_id')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario_perfil', to='proyecto.perfil')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_crud_perfil_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': True,
                'unique_together': {('perfil_id', 'usuario_id')},
            },
        ),
        migrations.CreateModel(
            name='PerfilModulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_modulo_modulo', to='proyecto.modulo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_modulo_perfil', to='proyecto.perfil')),
            ],
            options={
                'db_table': 'perfil_modulo',
                'managed': True,
                'unique_together': {('perfil_id', 'modulo_id')},
            },
        ),
    ]
