# Generated by Django 3.2.6 on 2023-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='fecha_termino',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_hasta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='fecha_desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='fecha_hasta',
            field=models.DateField(),
        ),
    ]
