# Generated by Django 3.2.6 on 2023-02-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoentrada',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
