# Generated by Django 3.2.6 on 2023-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ind_aprobado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
