# Generated by Django 3.2.6 on 2023-02-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_rename_tipo_tipoentrada_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoentrada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoentrada',
            name='ind_archivo',
            field=models.BooleanField(default=False),
        ),
    ]
