# Generated by Django 3.2.6 on 2023-03-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20230305_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrespuestaproyecto',
            name='ind_publicada',
            field=models.BooleanField(default=False),
        ),
    ]
