# Generated by Django 3.2.6 on 2023-02-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_proyecto_ind_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
