# Generated by Django 3.2.6 on 2022-12-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20221220_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='nombre',
        ),
    ]
