# Generated by Django 3.2.6 on 2022-12-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_seccion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='codigo',
            field=models.TextField(unique=True),
        ),
    ]
