# Generated by Django 3.2.6 on 2022-12-15 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioperfilactivo',
            unique_together={('perfil_id', 'usuario_id')},
        ),
    ]
