# Generated by Django 3.2.6 on 2022-12-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
