# Generated by Django 3.2.6 on 2022-12-15 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guard', '0002_alter_usuarioperfilactivo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='persona_estado_civil', to='guard.estadocivil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guard.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guard.sexo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_relation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
