version: '3'
services:
  db_postgres:
    image: 'postgres:11.5'
    restart: always
    volumes:
    - 'postgres_data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=nega
    - POSTGRES_PASSWORD=Nega6456519
    ports:
    - '5433:5433'
    container_name: db_postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django_app:
    build: .
    volumes:
      # - static:/sgpt/static
      - .:/sgpt
    depends_on:
      - db_postgres
    container_name: django_app

    command:
      - /bin/bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py implementacion
        python manage.py runserver 0.0.0.0:8081
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      # - static:/sgpt/static
    depends_on:
      - django_app
    container_name: nginx

volumes:
  .:
  postgres_data:
  # static: