version: '3'
services:
  db_postgres:
    image: 'postgres:11.5'
    restart: always
    volumes:
    - 'postgres_data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=nega
    - POSTGRES_PASSWORD=Nega6456519
    ports:
    - '5432:5432'
    container_name: db_postgres

volumes:
  .:
  postgres_data: